### ISSUE TITLE
Webgl crash, memory leak

### ISSUE THREAD

**Issue by HeadLessHUN** [potree/potree#628] opened 2019-03-23 19:53 UTC
Dear @m-schuetz 
Earlier there were several reports #585 #486  to ui crash which is still happens a lot of times if you move around in a big cloud. Desktop viewer seems a little bit better (maybe elektron optimalize more then regular browsers). Do you see any possible solution to these crashes in the future? I tried every output format bin, las,laz no matter which is used all crashes after a while (memory usage almost max). Maybe a temporarily solution would be to use a swap (virtual memory)?

Please note me if i can help you with anything to sort out the problem. I currently use latest stable 1.6 potreeConverter. Which is released a year ago. I didn't see any comment on this since then.

**Comment by mkasznia** [comment] 2019-04-05 17:18
Hey @HeadLessHUN !
Did you solve this problem maybe?  I've tried updating threeJS and other libs but with no success - still crashes after playing a bit.

**Comment by HeadLessHUN** [comment] 2019-04-05 22:19
I've revisited some LRU functions, and i figured out that during disposing elements only geometry gets disposed. Not the whole lruItem object this may be a leak but unfortunatelly i didn't have enough time and skill to make a differnce. Maybe together we can do something about that, if we discuss about it.

**Comment by HeadLessHUN** [comment] 2019-04-06 08:58
During the night i was able to define the problem.

Scene  (trheejs) objects are properly gets disposed, so that's not the problem. Our problem is that. The Octree nodes not get disposed each of them are 152 byte and you can imagine what happens if there were 330 000 nodes (one of our project is this big)... little math it requires 5GB ram just for the octreenodes which geometries are emptied, so its basicly useless...  Point clouds with 10 million pointbudget requires around additional 3-400 MB ram.

![potreeMemoryLeak](https://user-images.githubusercontent.com/10095691/55667256-286c5500-585a-11e9-8fdc-e4cea1419153.png)


these are just empty objects, with few information without event handler, geometry data.

**Comment by HeadLessHUN** [comment] 2019-04-06 12:01
Happy News...

I was able to solve one of the leaks, as it turned out there are more... i'll create a PR for that until that here is a solutution... I don't know if it has performance degradation, but at least we can see bigger clouds for more time...  :D
 I rewrote almost the whole disposeListener function but mostly the problem was that the point attributes didn't get disposed...

```
		let disposeListener = function () {
			let childIndex = parseInt(geometryNode.name[geometryNode.name.length - 1]);
			//check if sceneNode Deleted maybe can be removed for permformance gain it shouldn't be null
			if(sceneNode!==null){
				//check if has geometry it could be removed also...
				if(sceneNode.geometry){
					//delete attributes solve a big memory leak...
					for(let key in sceneNode.geometry.attributes){
							delete sceneNode.geometry.attributes[key];
					}
					//dispose geometry
					sceneNode.geometry.dispose();
					sceneNode.geometry=undefined;
				}
				//check if has material, can be removed...
				if(sceneNode.material){
					//check if has material map, can be removed...
					if(sceneNode.material.map){
						sceneNode.material.map.dispose();
						sceneNode.material.map=undefined;
						}
					//dispose material
					sceneNode.material.dispose();
					sceneNode.material=undefined;
				}
				//remove node from scene
				parent.sceneNode.remove(sceneNode);
				//set node explicitly undefined.
				sceneNode=undefined;
				parent.children[childIndex] = geometryNode;
			}
		};
```
I'll try to spot the other issue, but i fear that is the octree node one and it is require to understand the whole loading,reloading part, because simple dispose/delete children and nodes make the viewer not load new nodes...

**Comment by wemamawe** [comment] 2019-04-08 02:52
In PotreeRenderer.js file,at  renderNodes function,
```
let webglBuffer = null;
			if(!this.buffers.has(geometry)){
				webglBuffer = this.createBuffer(geometry);
				this.buffers.set(geometry, webglBuffer);
			}else{
				webglBuffer = this.buffers.get(geometry);
				for(let attributeName in geometry.attributes){
					let attribute = geometry.attributes[attributeName];

					if(attribute.version > webglBuffer.vbos.get(attributeName).version){
						this.updateBuffer(geometry);
					}
				}
			}
```
 the memory of vbos  always grow

**Comment by mkasznia** [comment] 2019-04-08 13:43
@HeadLessHUN I rly appreciate your job! I'll test your solution today and will try to dive into potree's code to find out other problems (however it may take me some time as I'm not JS developer).

**Comment by HeadLessHUN** [comment] 2019-04-08 16:28
I already created a pull request to develop branch. It solves one of the problem. And the cause of that is what you also found in PotreeRenderer class. it always recreate geometry attributes, and not dispose.  I'm also not a js developer. I found out in the developer branch there are lot of small bugs, so i use 1.6 instead. The fixes good for that version also..

**Comment by spirityy** [comment] 2019-07-11 10:32
@HeadLessHUN  thx,but problems still exist.
I have the same problem loading larger pointcould data. 
At the beginning, 
![mem1](https://user-images.githubusercontent.com/424997/61043700-7bc9e280-a409-11e9-83bf-7119504a897c.png)
After a while,
![mem3](https://user-images.githubusercontent.com/424997/61043717-84bab400-a409-11e9-8e59-b7d159c15dda.png)
The problem is PotreeRenderer class this.buffers? Or web workers load laz/las file cause memory leak?

**Comment by Jambofi76** [comment] 2020-04-29 06:14
@mkasznia you are right, the class Renderer in PotreeRenderer.js is the biggest problem. There is only createBuffer(geometry) and updateBuffer(geometry) for WebGLBuffer, but no deleteBuffer(geometry). The map buffers in this class only grows.
With the following changes the GPU Process memory in the showcase example chiller is not going above 500 MB and the Potree task memory is rising much slower. So there are still some other memory leaks to look for, but it takes longer for the user to crash the app.
I'm new to github and this project. @HeadLessHUN please verify my changes.

The PointCloudOctreeGeometryNode needs the Potree-Renderer, when it's disposed by the LRU. Therefore, the PotreeRenderer pRenderer has to be passed through some functions.

```
PotreeRenderer.js:

class Renderer {
     deleteBuffer(geometry) {
          let gl = this.gl;
          let webglBuffer = this.buffers.get(geometry);
          if (webglBuffer != null) {
                for (let attributeName in geometry.attributes) {
                     gl.deleteBuffer(webglBuffer.vbos.get(attributeName).handle);
                }
                this.buffers.delete(geometry);
          }
     }
}

PointCloudOctreeGeometry.cs:

class PointCloudOctreeGeometryNode {
     dispose(pRenderer){
          if (this.geometry != null && this.parent != null) {
                pRenderer.deleteBuffer(this.geometry);
                
                this.geometry.dispose();
                this.geometry = null;
                this.loaded = false;

                // this.dispatchEvent( { type: 'dispose' } );
                for (let i = 0; i < this.oneTimeDisposeHandlers.length; i++) {
                     let handler = this.oneTimeDisposeHandlers[i];
                     handler();
                }
                this.oneTimeDisposeHandlers = [];
          }
     }
}

LRU.js:

     freeMemory(pRenderer){
          if (this.elements <= 1) {
                return;
          }

          while (this.numPoints > Potree.pointLoadLimit) {
                let element = this.first;
                let node = element.node;
                this.disposeDescendants(node, pRenderer);
          }
     }

     disposeDescendants(node, pRenderer){
          let stack = [];
          stack.push(node);
          while (stack.length > 0) {
                let current = stack.pop();

                // console.log(current);

                current.dispose(pRenderer);
                this.remove(current);

                for (let key in current.children) {
                     if (current.children.hasOwnProperty(key)) {
                          let child = current.children[key];
                          if (child.loaded) {
                               stack.push(current.children[key]);
                          }
                     }
                }
          }
     }

potree_update_visibility.js:

export function updatePointClouds(pointclouds, camera, pRenderer){
     let renderer = pRenderer.threeRenderer;

     for (let pointcloud of pointclouds) {
          let start = performance.now();

          for (let profileRequest of pointcloud.profileRequests) {
                profileRequest.update();

                let duration = performance.now() - start;
                if(duration > 5){
                     break;
                }
          }

          let duration = performance.now() - start;
     }

     let result = updateVisibility(pointclouds, camera, renderer);

     for (let pointcloud of pointclouds) {
          pointcloud.updateMaterial(pointcloud.material, pointcloud.visibleNodes, camera, renderer);
          pointcloud.updateVisibleBounds();
     }

     exports.lru.freeMemory(pRenderer);

     return result;
};

viewer.js:

Viewer {

update(delta, timestamp){
     …
     if (!this.freeze) {
           let result = Potree.updatePointClouds(scene.pointclouds, camera, this.pRenderer);

     …
}

}

EDLRenderer.js:

class EDLRenderer {
     render(params){
          …
          if(this.screenshot){
                let oldBudget = Potree.pointBudget;
                Potree.pointBudget = Math.max(10 * 1000 * 1000, 2 * oldBudget);
                let result = Potree.updatePointClouds(
                     viewer.scene.pointclouds, 
                     camera, 
                     viewer.pRenderer);
                Potree.pointBudget = oldBudget;
          }
          …
}
}
``
```

**Comment by m-schuetz** [comment] 2020-04-29 06:25
Thanks for pointing out the buffers in PotreeRenderer, and suggestions for fixes. I'll have a look in the next few days.

**Comment by HeadLessHUN** [comment] 2020-05-11 07:46
@m-schuetz Did you have time to look into these suggestions? i didn't have any time for now. but as soon as i 've some time i'll try it out. I hope it is fairly easy to backport it to 1.6 version, because i use that for now.

**Comment by m-schuetz** [comment] 2020-05-11 12:34
@Jambofi76 @wemamawe @HeadLessHUN @mkasznia 

Thanks for the suggestions, the missing delete for attribute buffers on GPU were indeed a huge GPU memory leak. 

fixed with:
https://github.com/potree/potree/commit/47a27901bd5b3b61e5d4f29ac3706762eedd37b3
https://github.com/potree/potree/commit/1ba46afc60bbbb0ad0e81fcf8403ec23803b7281

**Closed** 2021-05-30 17:23 UTC
Labels: high-priority
