### ISSUE TITLE
Memory Leak with Large Point Clouds

### ISSUE THREAD

**Issue by CodeTherion** [potree/potree#793] opened 2020-04-17 12:00 UTC
Hello!

We've been using PoTree for a little while on some different scales of project. Recently we have been working on a solution that renders a point cloud on the scale of an entire Canadian Province. The viewer is handling this very well and honestly, I was stunned that it came out as well as it did. We have however discovered a significant Memory leak when operating at this scale.

Starting off:
![image](https://user-images.githubusercontent.com/6402075/79566471-fdc9f480-8088-11ea-9c6d-d4ab0a3287a4.png)

Any time we zoom in to an appropriate level to see the ground we gain roughly 200MB to 400MB of memory. This is acceptable as we are expecting to load higher-density segments of the OcTree. Navigating away from the area and zooming in to another area duplicates the memory as expected and triples visiting a third. However, it never cleans up after itself. Instead, we always seem to build up memory to the point of crashing the browser. What interests us is how the utility does seem to properly manage memory at rest. In general, we see both the root site and the GPU Process rise and fall in memory usage as the GC does properly run.

A few zoom ins later:
![image](https://user-images.githubusercontent.com/6402075/79566403-dffc8f80-8088-11ea-80f1-5d27b309d762.png)

My team and I have spent a week trying to track down where the leak is occurring and are now preparing to dig into PoTree itself. We will be happy to contribute the solution to the project when found. Would @m-schuetz or anyone be able to offer any assistance in the hunt or offer any leads to where we might dig in further?

Chrome: Version 81.0.4044.113
Stack: Angular -> NGINX
Data Host: Azure Blob Storage

- Tim

**Comment by HeadLessHUN** [comment] 2020-04-22 08:34
hello i've created some modifications for me its better but not solved.

there are other issues related to this.
#628 #667

**Comment by Jambofi76** [comment] 2020-04-29 06:20
@CodeTherion please look at #628

**Comment by m-schuetz** [comment] 2020-05-11 12:38
Closing this as duplicate of #628 #667. The GPU memory leak has now been fixed

**Closed by m-schuetz** 2020-05-11 12:38 UTC
