### ISSUE TITLE
MeasuringTool vertex can't be dragged in develop branch

### ISSUE THREAD

**Issue by sanak** [potree/potree#205] opened 2016-01-21 11:33 UTC
It seems not to work correctly after the following commit.
https://github.com/potree/potree/commit/08d7347d770c2861ccd6679ee26a049a83d42e7d

The following error messages were shown in Chrome Developer Tools.

<pre>
[GroupMarkerNotSet(crbug.com/242999)!:D03CD132E47F0000]GL ERROR :GL_INVALID_OPERATION : glDrawArrays: attempt to access out of range vertices in attribute 1
:
WebGL: too many errors, no more errors will be reported to the console for this context.
</pre>

**Comment by m-schuetz** [comment] 2016-01-22 03:59
Same as https://github.com/potree/potree/issues/202

Tried it with some of my point clouds but I can't reproduce the error. All of them work fine for me.
What parameters did you use for conversion and which version of PotreeConverter?

If you can upload an example or send me one (maybe downsampled with "-l 3") that would be helpful!

**Comment by sanak** [comment] 2016-01-22 04:56
Thanks for confirmation.
I also confirmed that the following environments were no problem (with examples/viewer.html).
- Windows 7 SP1 + Chrome
- Mac OSX (Yosemite) + Firefox

So, the cause seems to be Mac OSX Chrome specific WebGL issue.

**Comment by davijo** [comment] 2016-01-22 06:32
I get the same error on OSX Chrome (viewer+lion examples). Safari also stops working/picking after the first point picking though there is no informative messages related in the console.

I don't have the same issues (on OSX) with the latest dev branch on my local dev environment where Potree is used as a library.

**Comment by sanak** [comment] 2016-01-22 08:26
@davijo 
Thanks for information.
Are you using different version of three.js (r71) on your application ?
Because, I still encountered the problem with the latest "develop" branch.

**Comment by martinheidegger** [comment] 2017-08-17 14:34
This seems to be fixed. Closing the issue, please reopen if I am mistaken.

**Closed by martinheidegger** 2017-08-17 14:34 UTC
