### ISSUE TITLE
bringing potree to VR

### ISSUE THREAD

**Issue by omidfaraji** [potree/potree#352] opened 2017-06-26 14:34 UTC
Hi. i want to use potree with VR.
i tested this like with HTC VIVE .
[https://github.com/eokeeffe/potree_vr](url)
but it does not work correctly.

do you know if there is any implementation of potree for VR ?
or any help to implement it by myself?

**Comment by jo-chemla** [comment] 2017-06-26 14:51
See development here : https://github.com/potree/potree/issues/292

**Comment by omidfaraji** [comment] 2017-06-26 15:20
in this issue the only solution that works is this:
[https://github.com/eokeeffe/potree_vr](url)
i tested example of potree_vr but i can not see any thing in HTC VIVE headset.
had you test it ?
does it work correctly?

**Comment by martinheidegger** [comment] 2017-08-21 12:59
This is a duplicate of #292 . Closing it. Please continue the discussion in #386 and/or #292

**Closed by martinheidegger** 2017-08-21 12:59 UTC
Labels: enhancement
